### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by francismanjares** [Excrulon/Tree-of-Savior-Addon-Manager#1]
How can one run this amazing addon-manager?

**Comment by Excrulon** [comment]
Extract zip somewhere and run the .exe in the folder.

**Comment by francismanjares** [comment]
umm.. I don't see any exe file on the zipped file :(

**Comment by Excrulon** [comment]
`Tree of Savior Addon Manager.exe`

**Comment by Excrulon** [comment]
Chrome might be lame and remove .exes... hmm.

**Comment by francismanjares** [comment]
oh found the zip file on the release section:D thanks thanks thanks :)
