### ISSUE TITLE
ToS addon manager - addon "uninstall" bug

### ISSUE THREAD

**Issue by ejayrai11** [Excrulon/Tree-of-Savior-Addon-Manager#10]
i deleted the addon folder and .ipf file on TOS folder....
and when i run the addon manager , the uninstall button is still there and i cant reinstall the addons using the manager. even if i click the unintall button, it doesnt revert to the install button.

the addon manager doesnt detect if the addon files and ipf files are deleted... it still considers them as installed even though i already deleted them from the tos folder.

and the block message and clear chat for the bot spammers, is it available on tos addon manager? i installed them all but that function is missing.

pardon my english and hope you understand what i mean.. >.<

**Comment by Xanaxiel** [comment]
Which specific addon are you having problems with uninstall?

**Comment by ejayrai11** [comment]
all the addons that i installed.

**Comment by Excrulon** [comment]
read instructions/faq

**Comment by ejayrai11** [comment]
There are two files here named settings.json and addons.json. settings.json is responsible for saving your Tree of Savior directory location. addons.json is responsible for keeping track of the addons you have installed. If something goes wrong and things get out of sync, either manually make the changes in this file or delete that file and the installed ipfs manually and start over. Hopefully you won't really have to do this.

hahaha... found it. >.<
teehee.... 

and about my other question, how do i enable that block chat?

**Comment by ejayrai11** [comment]
![asdasdasdasdasdasdasd](https://cloud.githubusercontent.com/assets/19761731/15806332/a4d9ef74-2b73-11e6-93ff-5f10252c5ac4.png)

looks like this. the manager still shows uninstall button even if the addons in the game folder is already deleted. note: i deleted it directly/manually not  using the manager.
