### ISSUE TITLE
cant update

### ISSUE THREAD

**Issue by kanadecan** [Excrulon/Tree-of-Savior-Addon-Manager#11]
just found few hours ago some adds on have newer version, but when i click update, it didnt respond, and no upgrade at all, its my addon manager problem, or there is any solution?
![addon](https://cloud.githubusercontent.com/assets/13523306/15807933/f628ae18-2b93-11e6-8f95-2aac94e9fa4d.png)

**Comment by Excrulon** [comment]
Does the file exist? Sounds like you probably deleted the ipf manually.

**Comment by kanadecan** [comment]
ipf at my tos folder? its still there.

![ipf](https://cloud.githubusercontent.com/assets/13523306/15810308/383c8b5c-2bc7-11e6-8969-5d45e7d3187f.png)

**Comment by Miei** [comment]
Uh, the versions that you have in your data folder are not installed by addon manager... You're trying to update Cabinet Commas and Classic Chat, where are their ipf files?

Well anyway, you can solve this by deleting `addons.json` in `%appdata%\tree-of-savior-addon-manager` and reinstalling the ipf files via addon manager. I'd recommend removing those old versions from your data folder and installing the versions from addon manager, too..
