### ISSUE TITLE
Where is the block & report addon that was in the previous version

### ISSUE THREAD

**Issue by fishhy123** [Excrulon/Tree-of-Savior-Addon-Manager#12]
Hi, previously I used your addon on [https://github.com/Excrulon/Tree-of-Savior-Addons/releases/tag/1.9](url) that contain “Block and Report” feature.

But when using this manager I cant find which addon has it. Do u know where can I find it?

**Comment by Miei** [comment]
It hasn't been updated for the addon manager yet, there are some issues that need to be fixed with it. Since it was mostly written by me, I should be the one to fix it but I'm a little busy with other things lately. Maybe I'll get around to it.

**Comment by Excrulon** [comment]
I kept putting off looking into it cause busy with so much other stuff. Feel free to move it to your repo since you did it all anyway!

**Comment by Miei** [comment]
Added to addon manager under the name "Context Menu Additions" @fishhy123

**Comment by fishhy123** [comment]
Thank you so much! @miei
