### ISSUE TITLE
HEY! how to edit .lua file (zoomy)

### ISSUE THREAD

**Issue by metorika** [Excrulon/Tree-of-Savior-Addon-Manager#13]
let say I want to edit my config files like zoom_amount, current_zoom. before this addon theres a file name zoomy.lua which I can edit this value, but now they r all gone.....how to bring them back

and Exrulon don't you see what we have reported here? zoomy got reset after cutscence or bossfight, this mod has problem. do u even care fixing this? or at least answer something? FFS

**Comment by Excrulon** [comment]
Yeah fuck off. I don't owe you anything, I do this as a hobby in my free
time. Some people... FFS YO!

**Comment by WillTheDoggy** [comment]
AYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY LMAO.

**Comment by fiote** [comment]
<img src='http://www.nearingkolob.com/wp-content/uploads/2015/05/savage-2-500x173.jpg' />
