### ISSUE TITLE
About translations

### ISSUE THREAD

**Issue by HoNatNat** [Excrulon/Tree-of-Savior-Addon-Manager#16]
Hi, I'm from Hong Kong.
I am wondering if you have any interested in translating Traditional Chinese for Taiwan-HongKong-Macau Server?
Please contact me if you are interested. I can help with the translation part.

For your reference, I only contacted MizukiBelhi (Author of ExtendedUI) about this.
Because I don't really know do I need to contact every author after I contacted you.
Thank you very much & looking forward to your reply.

**Comment by Excrulon** [comment]
If you want to do all the coding to support translations and make a pull request, you're welcome to. I'm not spending any time on it.
