### ISSUE TITLE
Problem on "Show Invested Stat Points v1.0.1" addon

### ISSUE THREAD

**Issue by reaperhack** [Excrulon/Tree-of-Savior-Addon-Manager#17]
hi, i used previous version (i believe it is v1.0) and it works properly. then i update it to v1.0.1 but it doesn't show anything like this. http://i.imgur.com/OZdGWbX.jpg
i installed via addon manager btw.

**Comment by Xanaxiel** [comment]
Just revert to the old version, the fix was intended for iToS only
