### ISSUE TITLE
Uninstall bug.

### ISSUE THREAD

**Issue by blkldxl** [Excrulon/Tree-of-Savior-Addon-Manager#18]
i uninstall TOS and then delete all folders, because im getting kicked from the server. now i try to install addon manager and say "uninstall" the addon when is deleted yet. what i need to do i read other issues but nothing work. what i should delete?

**Comment by Halvaard** [comment]
Instructions per Readme file:
* Starting over

If things ever get out of sync from some reason, you can find settings and addon cache in `%AppData%\Tree of Savior Addon Manager`. Open the run prompt or Windows Explorer and type that path in to open it.

There are two files here named `settings.json` and `addons.json`. `settings.json` is responsible for saving your Tree of Savior directory location. `addons.json` is responsible for keeping track of the addons you have installed. If something goes wrong and things get out of sync, either manually make the changes in this file or delete that file and the installed ipfs manually and start over. Hopefully you won't really have to do this.

**Comment by Excrulon** [comment]
yeah just delete addons.json. I'll fix it someday when I feel like putting time into this again.

**Comment by mtvbutsu** [comment]
Excrulon tos banned me for 1 month only to use the addons

**Comment by mtvbutsu** [comment]
Excrulon tos banned me for 1 month only for use the addons, you still feel secure in using them?

**Comment by mtvbutsu** [comment]
Excrulon tos banned me for 1 month only for use the addons, you still feel secure in using them?

**Comment by mtvbutsu** [comment]
Excrulon tos banned me for 1 month only for use the addons, you still feel secure in using them?

**Comment by mtvbutsu** [comment]
Excrulon tos banned me for 1 month only for use the addons, you still feel secure in using them?

**Comment by mtvbutsu** [comment]
Excrulon tos banned me for 1 month only for use the addons, you still feel secure in using them?

**Comment by mtvbutsu** [comment]
Excrulon tos banned me for 1 month only for use the addons, you still feel secure in using them?

**Comment by mtvbutsu** [comment]
Excrulon tos banned me for 1 month only for use the addons, you still feel secure in using them?

**Comment by mtvbutsu** [comment]
Excrulon tos banned me for 1 month only for use the addons, you still feel secure in using them?

**Comment by mtvbutsu** [comment]
Excrulon tos banned me for 1 month only for use the addons, you still feel secure in using them?

**Comment by mtvbutsu** [comment]
Excrulon tos banned me for 1 month only for use the addons, you still feel secure in using them?

**Comment by Excrulon** [comment]
No one has gotten banned for using any of my addons.

**Comment by mtvbutsu** [comment]
I never use bots or others addons, only use your addons and get ban... I DONT UNDESTAND WHY???

**Comment by Excrulon** [comment]
no idea. open a ticket with imc.

**Comment by mtvbutsu** [comment]
21 tickets hehehehehe and nothing answer in 1 month.
Another thing the character with addons simply stops moving, what is this ??? now I uninstalled addons and the char was not locked

**Comment by TehSeph** [comment]
You're either trolling or just plain retarded. It's not the addons. Stop spamming this issue with your nonsense and take it up with IMC.

**Comment by mtvbutsu** [comment]
shut up your shit, you are a woman it ???

To talking to him the reality, only use the addons that he passed. I do not use bot, not explore bugs and not use trickery and won ban 1 month. was playing now and the char was simply locked in the scenario, it is really a problem that is directly on addons .... uninstalled and the game is normal

Excrulon .... I'm telling the truth !!!

TEHSEPH FAG ..... SHUT UP YOUR SHIT!
