### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Mookiefire** [Excrulon/Tree-of-Savior-Addon-Manager#2]
When I downloaded the manager it had some of the addon on uninstall and I was unable to install the ones that was checked as uninstall i was able to download the ones that said install i even try to redownload to see if it would fix it but did not is there a way to reset it or I have to wait for new updates?

**Comment by Excrulon** [comment]
I don't understand what you're asking...

**Comment by Mookiefire** [comment]
I'm saying this the tab to click install is stuck as uninstall it does not show install like the rest when I click uninstall nothing happens

**Comment by Excrulon** [comment]
Post a video of it happening if you can, I guess. I still don't follow.

**Comment by Mookiefire** [comment]
found out the problem when one of the "ipf" from "better quest" got remove it ended up making the program think I still had it installed when I didn't its working now. great addon manager tho very useful when I'm very lazy in downloading stuff.

**Comment by Excrulon** [comment]
Great, thanks.
