### ISSUE TITLE
not working for standalone tos from playone.asia

### ISSUE THREAD

**Issue by serious96** [Excrulon/Tree-of-Savior-Addon-Manager#3]
hello excrulon, thank you for making this great add on, but sadly i;m not playing in steam server, rather i'm playing in playone.asia. I hope u can make the add on compatible with the TOS from playone.asia

**Comment by Excrulon** [comment]
I don't have the capability to support that. Why wouldn't it work? Addons should load just the same. Did standalone addons work in the past?

**Comment by serious96** [comment]
Sorry Excrulon, it's my fault for not trying it first. I can specify tos directory and install from the browse section fine, but when i click launch tree of savior from the add on manager, it won't open tos.exe from the specified directory, rather it will open steam to play tos (I have two different tos installation, one from the steam, and the other from the playone.asia, both are in different folder obviously). And for the addons, everything work perfectly without problem. Aside from the minor problem mentioned before, the addon manager it self just working fine.

**Comment by Excrulon** [comment]
The launch button only works for the steam version since it specifically uses the steam url of `steam://rungameid/372000`. You'll just have to launch the game how you always have for now.
