### ISSUE TITLE
win 32bit

### ISSUE THREAD

**Issue by tqk2811** [Excrulon/Tree-of-Savior-Addon-Manager#5]
Hello Excrulon!
Can you make a version for window 32bit (x86)?

Or bug?
My window: win7 32bit but get error
Image: https://goo.gl/photos/F76VYsRJoHdnrqk58

Thank.

**Comment by Excrulon** [comment]
All future releases will be x86. I can't believe people are still using x86, haha.

**Comment by Excrulon** [comment]
[Latest release](https://github.com/Excrulon/Tree-of-Savior-Addon-Manager/releases/latest) should be x86.
