### ISSUE TITLE
ExtendedUI Settings Bug

### ISSUE THREAD

**Issue by roflmbo** [Excrulon/Tree-of-Savior-Addon-Manager#7]
I am able to set a modified location for everything except the target frame and targets buffs frame. I move the target frame to new coordinates, hit save, and close the ExtendedUI Settings. After I mouse over a new target the target frame moves back to the default location. Reopening the ExtendedUI Settings makes it reappear in the modified location. It seems like the changes are not being retained when I close the ExtendedUI Settings. I have only noticed this issue with the target frame and target buffs frame. Everything else is retaining the custom coordinates properly, as far as I can tell.

I just reinstalled the game and cleared out the old directory. I installed the newest versions of the majority of the mods using the addon manager.

You can see the frame jumping from one location to another when I have the ExtendedUI Settings open and when it is closed.
![20160603035902_1](https://cloud.githubusercontent.com/assets/5403051/15774148/79571bd6-2940-11e6-8157-7be14c323352.jpg)
![20160603035910_1](https://cloud.githubusercontent.com/assets/5403051/15774156/7e3b40d2-2940-11e6-90a1-427b8c57fe20.jpg)

**Comment by MizukiBelhi** [comment]
Try here maybe? https://github.com/MizukiBelhi/ExtendedUI/issues
This has nothing to do with addon manager.

**Comment by roflmbo** [comment]
Thanks.
