### ISSUE TITLE
Error when opening

### ISSUE THREAD

**Issue by vitortexc** [Excrulon/Tree-of-Savior-Addon-Manager#9]
I get this error when opening the program:

![error](https://cloud.githubusercontent.com/assets/13662204/15796406/661a2764-29d3-11e6-97f7-f5ff2b53ee5b.png)

Just say if and what info you need.

**Comment by Excrulon** [comment]
Beats me... weird.

**Comment by vitortexc** [comment]
I did a test and commented the "electron.crashReporter.start();" line(7)  in main.js.
Everything worked fine.

It's seems to be an error with electron itself and not your app.
If this line was only to send errors back to de devs you could give an option to enable or disable this function. I don't know.

By the way, good job in those addons.
